# Generated by Django 5.1.4 on 2025-01-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь сервиса библиотеки",
                "verbose_name_plural": "Пользователи сервиса библиотеки",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Введите Ваш адрес",
                max_length=400,
                null=True,
                verbose_name="Адрес",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Введите Вашу дату рождения",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True,
                help_text="Введите Ваше отчество",
                max_length=50,
                null=True,
                verbose_name="Отчество",
            ),
        ),
    ]
